use_frameworks!

target 'SelfSizingCollectionViewController_Example' do
  pod 'SelfSizingCollectionViewController', :path => '../'

  target 'SelfSizingCollectionViewController_Tests' do
    inherit! :search_paths

    
  end
end
